### PR TITLE
added pet index route controller and view

### PR DESCRIPTION
**Pull request by akihoH**
I added index page for pet model

please check it by going to (http://localhost:3000/pets)

### CODE REVIEW

**Review by ValentinIbanescu — COMMENTED** [review]
Looks great! 🐈🐈‍⬛👋🏻👍🏻
Typo: Sprcies

**Comment by akihoH** [comment]
fixed the typo

**Comment by akihoH** [comment]
fixed the typo

**Review by ValentinIbanescu — APPROVED** [review]
Sehr gut!👍🏻

**Pull request merged**
